version: '3.8'

services:
  pastiepie:
    build: .
    container_name: pastiepie_app
    ports:
      - "8080:8080"  # Publicly expose port 8080 (Nginx will handle traffic)
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      DB_PATH: "/root/data"
      AES_KEY: "${AES_KEY}"
    volumes:
      - ./data:/root/data  # Persist data across restarts
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Use custom nginx config
      - ./supervisord.conf:/etc/supervisord.conf  # Use Supervisor configuration
    restart: unless-stopped
