version: '3.8'

services:
  pastiepie:
    build: .
    container_name: pastiepie_app
    ports:
      - "80:80"  # Expose port 80 (Nginx will handle HTTP traffic)
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"  # Application log level (set in .env or passed at runtime)
      DB_PATH: "/root/data"       # Path to store database files
      AES_KEY: "${AES_KEY}"       # AES encryption key (set in .env or passed at runtime)
    volumes:
      - ./data:/root/data                        # Persist SQLite data across restarts
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Custom Nginx configuration
      - ./supervisord.conf:/etc/supervisord.conf # Custom Supervisor configuration
    restart: unless-stopped                      # Restart service unless explicitly stopped
